grpc:
  client:
    balance-service:
      address: static://localhost:9090
      negotiation-type: TLS
      security:
        trust-cert-collection: classpath:certificates/server.crt
    account-service:
      address: static://localhost:9090
      negotiation-type: TLS
      security:
        trust-cert-collection: classpath:certificates/server.crt
    transaction-service:
      address: static://localhost:9090
      negotiation-type: TLS
      security:
        trust-cert-collection: classpath:certificates/server.crt