grpc:
  client:
    balance-service:
      address: static://localhost:9090
      negotiation-type: PLAINTEXT
    account-service:
      address: static://localhost:9090
      negotiation-type: PLAINTEXT
    transaction-service:
      address: static://localhost:9090
      negotiation-type: PLAINTEXT